App/Controllers/ProgramsController.cs
    using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using App.Filters;
using App.Models;
using App.viewmodel;

namespace App.Controllers
{
    //[Authorize, SessionExpire]
    public class ProgramsController : Controller
    {
        private m1TestEntities db = new m1TestEntities();

        // GET: ProgramMaster
        public ActionResult Index(long? id)
        {
            List<ProgramViewModel> ObjProgramList = new List<ProgramViewModel>();
            try
            {

        
            ObjProgramList = (from c in db.tbl_ProgramMaster
                    
                       select new ProgramViewModel()
                       {
                           pkProgramId = c.pkProgramId,
                           ImageUrl = c.ImageUrl,
                           Name = c.Name,
                           Session = c.Session,
                           AudioTrackCount = (from pl in db.tbl_ProgramPlayList where pl.fkProgramId == c.pkProgramId && pl.PlayListType == 2 && ((pl.IsBonusTrack == null ? false : pl.IsBonusTrack) == false) select pl).Count(),
                           TextCount = (from pl in db.tbl_ProgramPlayList where pl.fkProgramId == c.pkProgramId && pl.PlayListType ==1 && ((pl.IsBonusTrack == null ? false : pl.IsBonusTrack) == false) select pl).Count(),
                           BonusTrack = (from pl in db.tbl_ProgramPlayList where pl.fkProgramId == c.pkProgramId && pl.IsBonusTrack == true select pl).Count(),
                           IsProgramUnlockForAllUser = c.IsProgramUnlockForAllUser ?? false
                       }).ToList();
            }
            catch (Exception ex)
            {
                string exception = ex.ToString();


            }
            return View(ObjProgramList);
            // return View(db.tbl_ProgramMaster.ToList());
        }

        // GET: ProgramMaster/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_ProgramMaster tbl_ProgramMaster = db.tbl_ProgramMaster.Find(id);
            if (tbl_ProgramMaster == null)
            {
                return HttpNotFound();
            }
            return View(tbl_ProgramMaster);
        }

        // GET: ProgramMaster/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProgramMaster/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Create( tbl_ProgramMaster tbl_ProgramMaster, HttpPostedFileBase file)
        {
            string fileName = string.Empty;
            string destinationPath = string.Empty;
            //if (ModelState.IsValid)
            //{
            //    db.tbl_ProgramMaster.Add(tbl_ProgramMaster);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file_Uploader = Request.Files[0] as HttpPostedFileBase;
                if (file_Uploader.ContentLength > 0)
                {

                    fileName = file_Uploader.FileName;
                    destinationPath = Path.Combine(Server.MapPath("~/Upload/ProgramImages/ActiveProgram/"), fileName);
                    file_Uploader.SaveAs(destinationPath);
                    tbl_ProgramMaster.ImageUrl = fileName;


                }
                else
                {

                    tbl_ProgramMaster.ImageUrl = "defaultProgram.png";

                }
                tbl_ProgramMaster.CreatedDate = DateTime.Now;
                tbl_ProgramMaster.CreatedBy = "ADMIN";
                db.tbl_ProgramMaster.Add(tbl_ProgramMaster);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_ProgramMaster);
        }

        // GET: ProgramMaster/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_ProgramMaster tbl_ProgramMaster = db.tbl_ProgramMaster.Find(id);
            if (tbl_ProgramMaster == null)
            {
                return HttpNotFound();
            }
            return View(tbl_ProgramMaster);
        }

        // POST: ProgramMaster/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "pkProgramId,Name,Description,ImageUrl,Session")] tbl_ProgramMaster tbl_ProgramMaster)
        {
            string fileName = string.Empty;
            string destinationPath = string.Empty;
            tbl_ProgramMaster Result = db.tbl_ProgramMaster.Where(x => x.pkProgramId == tbl_ProgramMaster.pkProgramId).FirstOrDefault();
            if (ModelState.IsValid)
            {

                HttpPostedFileBase file_Uploader = Request.Files[0] as HttpPostedFileBase;
                if (file_Uploader.ContentLength > 0)
                {
                    if (!Result.ImageUrl.Contains("defaultProgram"))
                    {
                        int pos = Result.ImageUrl.LastIndexOf("/") + 1;
                        fileName = Result.ImageUrl.Substring(pos, Result.ImageUrl.Length - pos);
                        destinationPath = Path.Combine(Server.MapPath("~/Upload/ProgramImages/ActiveProgram/"), fileName);

                        if (System.IO.File.Exists(destinationPath))
                        {
                            System.IO.File.Delete(destinationPath);
                        }

                    }



                    fileName = file_Uploader.FileName;
                    destinationPath = Path.Combine(Server.MapPath("~/Upload/ProgramImages/ActiveProgram/"), fileName);
                    file_Uploader.SaveAs(destinationPath);
                    Result.Name = tbl_ProgramMaster.Name;
                    Result.Description = tbl_ProgramMaster.Description.Replace("&nbsp;", " ");
                    Result.ImageUrl = fileName;
                    Result.Session = tbl_ProgramMaster.Session;
                    

                }
                else
                {
                    Result.Name = tbl_ProgramMaster.Name;
                    Result.Description = tbl_ProgramMaster.Description.Replace("&nbsp;", " ");
                    Result.ImageUrl = Result.ImageUrl;
                    Result.Session = tbl_ProgramMaster.Session;
                 
           

                }
                Result.CreatedDate = DateTime.Now;
                db.Entry(Result).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_ProgramMaster);
        }




        public ActionResult GetPaymentData()
        {

            List<ProgramViewModel> ObjProgramList = new List<ProgramViewModel>();
            try
            {


                ObjProgramList = (from c in db.tbl_ProgramMaster

                                  select new ProgramViewModel()
                                  {
                                      pkProgramId = c.pkProgramId,
                                      ImageUrl = c.ImageUrl,
                                      Name = c.Name,
                                      Price = c.Price,
                                      PaymentText = c.PaymentText,
                                  }).ToList();
            }
            catch (Exception ex)
            {
                string exception = ex.ToString();


            }
            return View(ObjProgramList);

        }

        public ActionResult EditPaymentData(long? id)
        {
            tbl_ProgramMaster ObjProgramList = new tbl_ProgramMaster();
            try
            {
                ObjProgramList = db.tbl_ProgramMaster.Find(id);

            }
            catch (Exception ex)
            {

                string exception = ex.ToString();
            }
            return View(ObjProgramList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult CreateProgramEdit(tbl_ProgramMaster tbl_ProgramMaster)
        {
            if (ModelState.IsValid)
            {
                tbl_ProgramMaster Result = db.tbl_ProgramMaster.Where(x => x.pkProgramId == tbl_ProgramMaster.pkProgramId).FirstOrDefault();

                Result.PaymentText = tbl_ProgramMaster.PaymentText;
                Result.Price = tbl_ProgramMaster.Price;
                Result.Name = tbl_ProgramMaster.Name;
                db.Entry(Result).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("GetPaymentData");
        }


        // GET: ProgramMaster/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_ProgramMaster tbl_ProgramMaster = db.tbl_ProgramMaster.Find(id);

App/Views/Programs/Create.cshtml
@model App.Models.tbl_ProgramMaster

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}

<h2>Create Programs</h2>

@using (Html.BeginForm("Create", "Programs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextArea("Description", new {  @class = "textarea form-control",
               rows = "10",   style = "width:50%;" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { Type = "File" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Session, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Session, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Session, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

App/Views/Programs/Delete.cshtml
@model App.Models.tbl_ProgramMaster

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Program</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Session)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

App/Views/Programs/Details.cshtml
@model App.Models.tbl_ProgramMaster

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Program</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Session)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.pkProgramId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

App/Views/Programs/Edit.cshtml
@model App.Models.tbl_ProgramMaster

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}

<h2>Edit Program</h2>
@using (Html.BeginForm("Edit", "Programs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.pkProgramId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextArea("Description", new {  @class = "textarea form-control", rows = "10",   style = "width:50%;" })
                @*@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@if (!String.IsNullOrEmpty(Model.ImageUrl))
                {
                    <img src="@Url.Content("~/Upload/ProgramImages/ActiveProgram/" + Model.ImageUrl)" width="30%" alt="" />
                }*@
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { Type = "File" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Session, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Session, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Session, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

App/Views/Programs/EditPaymentData.cshtml
@model App.Models.tbl_ProgramMaster

<h2>Edit Program</h2>
@using (Html.BeginForm("CreateProgramEdit", "Programs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.pkProgramId)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PaymentText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextArea("PaymentText", new { @class = "textarea form-control", rows = "10", style = "width:50%;" })
            @Html.ValidationMessageFor(model => model.PaymentText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

</div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

}


App/Views/Programs/GetPaymentData.cshtml
@*@model IEnumerable<App.Models.tbl_ProgramMaster>*@
@model IEnumerable<App.viewmodel.ProgramViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}
<script src="~/Scripts/jquery-3.3.1.js"></script>

<h2 class="user_listing-head">Programs</h2>


<div class="box-body table-responsive no-padding">
    <table class="table table-hover">
        <tr>
            <th>Name  </th>
          
            <th> Text</th>
            <th>Price  </th>
            <th>Action</th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>@Html.DisplayFor(modelItem => item.PaymentText)</td>
            <td>@Html.DisplayFor(modelItem => item.Price)</td>

            <td>
                @Html.ActionLink("Edit", "EditPaymentData", new { id = item.pkProgramId }) 
            

            </td>
        </tr>
        }


    </table>
</div>


App/Views/Programs/Index.cshtml
@*@model IEnumerable<App.Models.tbl_ProgramMaster>*@
@model IEnumerable<App.viewmodel.ProgramViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}
<script src="~/Scripts/jquery-3.3.1.js"></script>

<h2 class="user_listing-head">Programs</h2>

<p class="create__new-program">
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i> @Html.ActionLink("Create New", "Create")
</p>
<div class="box-body table-responsive no-padding">
    <table class="table table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)

            </th>
            <th>
                Audio Tracks
            </th>
            <th>
                Text Tracks
            </th>
            <th>
                Bonus Tracks
            </th>
            <th align="center" class="text-center">
                Images

            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Session)*@
                Total Sessions
            </th>
            <th align="center" class="text-center">
                Lock status
            </th>
            <th>Action</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AudioTrackCount)

                    @Html.ActionLink("Track", "AudioIndex", "AdminTrack", new { id = item.pkProgramId }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TextCount)
                    @Html.ActionLink("Track", "TextIndex", "AdminTrack", new { id = item.pkProgramId }, null)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BonusTrack)
                    @Html.ActionLink("Track", "Audiotrackviewlist", "BonusTrackAdmin", new { id = item.pkProgramId }, null)

                </td>

                <td align="center">
                    <img class="table-img-logos" src="@Url.Content("~/Upload/ProgramImages/ActiveProgram/" + item.ImageUrl)" width="100%" alt="" />
                    @*@Html.Image(item.ImageUrl, "")
                        @Html.Image(modelItem => "Upload/ProgramImages/ActiveProgram/" + item.ImageUrl)*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Session)
                </td>
                <td>
                    @Html.CheckBoxFor(modelItem => item.IsProgramUnlockForAllUser, htmlAttributes: new { @checked = item.IsProgramUnlockForAllUser, @class = "checkbox_" + item.pkProgramId })
                    @if (item.IsProgramUnlockForAllUser)
                    {
                        <labe>This Program is Unlocked</labe>
                    }
                    else
                    {
                        <labe>This Program is Locked</labe>
                    }

                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedBy)
                    </td>*@
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.pkProgramId }) |
                    @*@Html.ActionLink("Details", "Details", new { id = item.pkProgramId }) |*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.pkProgramId })

                </td>
            </tr>
        }


    </table>
</div>
<script>
    $(document).ready(function () {
        $('input[type="checkbox"]').click(function () {

            var classProgram = $(this).attr('class');
            var pkProgramId = $(this).attr('class').split("_")[1]

            var dataModel = { IsProgramUnlockForAllUser: $(this).prop("checked"), pkProgramId: pkProgramId };
            $.ajax({
                url: "/Programs/ActiveInactiveProgram",
                type: "POST",
                data: dataModel,
                dataType: 'json',
                success: function () {
                      location.reload(true);
                },
                error: function (error) {
                    console.log(error);
                      location.reload(true);
                }
            });



        });
    });



</script>