App/Controllers/BonusTrackAdminController.cs
using App.Filters;
using App.Models;
using App.viewmodel;
using Microsoft.WindowsAPICodePack.Shell;
using Microsoft.WindowsAPICodePack.Shell.PropertySystem;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace App.Controllers
{
    [Authorize, SessionExpire]
    public class BonusTrackAdminController : Controller
    {
        private m1TestEntities db = new m1TestEntities();
        string Host = ConfigurationManager.AppSettings["Host"].ToString();
        // GET: BonusTrackAdmin
        public ActionResult Audiotrackviewlist(long? id)
        {

            List<ProgramPlayListViewModel> ObjProgramPlayList = new List<ProgramPlayListViewModel>();
            using (db = new m1TestEntities())
            {
                ObjProgramPlayList = (from c in db.tbl_ProgramPlayList
                                      where c.fkProgramId == id && c.PlayListType == 2 && c.IsBonusTrack == true
                                      select new ProgramPlayListViewModel()
                                      {
                                          pkProgramPlayListId = c.pkProgramPlayListId,
                                          PlayList = c.PlayList,
                                          CreatedBy = c.CreatedBy,
                                          Description = c.Description,
                                          TrackArtist = c.TrackArtist,
                                          TrackUrl = c.PlayListUrl,
                                          TrackTimeCount = c.TrackDuration,
                                      }).ToList();


            }


            TempData["ProgramId"] = id;

            return View(ObjProgramPlayList);
        }

        public ActionResult Create()
        {
            if (TempData["ProgramId"] != null)
            {
                int ProgramId = Convert.ToInt32(TempData["ProgramId"]);
                ViewBag.ProgramId = ProgramId;
                TempData["ProgramId"] = ProgramId;
            }
            else
            {
                return RedirectToAction("Index", "Programs");
            }
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Create(ProgramPlayListViewModel tbl_ProgramPlayListModel, HttpPostedFileBase file)
        {

            long ProgramId = 0;
            tbl_ProgramPlayList Objtbl_ProgramPlayList = new tbl_ProgramPlayList();

            string fileName = string.Empty;
            string guidwithFile = string.Empty;
            string destinationPath = string.Empty;
            string strpath = string.Empty;
            try
            {
                using (var db = new m1TestEntities())
                {
                    ProgramId = int.Parse(TempData["ProgramId"].ToString());
                    var Result = db.tbl_ProgramMaster.Where(x => x.pkProgramId == ProgramId).FirstOrDefault();
                    if (ModelState.IsValid)
                    {
                        HttpPostedFileBase file_Uploader = Request.Files[0] as HttpPostedFileBase;
                        if (file_Uploader.ContentLength > 0)
                        {

                            fileName = Path.GetFileName(file_Uploader.FileName).Replace("_", "-");
                            guidwithFile = Guid.NewGuid().ToString().Substring(0, 20).Replace("_", "-");
                            strpath = System.IO.Path.GetExtension(file_Uploader.FileName);
                            guidwithFile = guidwithFile + strpath; ;

                            bool exists = System.IO.Directory.Exists(Path.Combine(Server.MapPath("~/Upload/" + Result.Name)));
                            if (!exists)
                            {
                                System.IO.Directory.CreateDirectory(Path.Combine(Server.MapPath("~/Upload/" + Result.Name)));
                            }
                            destinationPath = Path.Combine(Server.MapPath("~/Upload/" + Result.Name + "/"), guidwithFile);
                            file_Uploader.SaveAs(destinationPath);


                        }
                        string tracktime = string.Empty;
                        string[] arr = new string[] { ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp" };
                     if (!arr.Contains(strpath))
                        {
                            using (var shell = ShellObject.FromParsingName(destinationPath))
                            {
                                IShellProperty prop = shell.Properties.System.Media.Duration;
                                var t = (ulong)prop.ValueAsObject;
                                tracktime = TimeSpan.FromTicks((long)t).ToString();
                            }
                        }

                        Objtbl_ProgramPlayList.fkProgramId = ProgramId;
                        Objtbl_ProgramPlayList.PlayList = string.IsNullOrEmpty(tbl_ProgramPlayListModel.PlayList) ? fileName : tbl_ProgramPlayListModel.PlayList;
                        Objtbl_ProgramPlayList.PlayListUrl = Result.Name + "/" + guidwithFile;
                        Objtbl_ProgramPlayList.PlayListType = 2;
                        Objtbl_ProgramPlayList.CreatedDate = DateTime.UtcNow;
                        Objtbl_ProgramPlayList.CreatedBy = "ADMIN";
                        Objtbl_ProgramPlayList.TrackArtist = tbl_ProgramPlayListModel.TrackArtist;
                        Objtbl_ProgramPlayList.Description = tbl_ProgramPlayListModel.Description.Replace("&nbsp;", " "); 
                        Objtbl_ProgramPlayList.TrackDuration = tracktime.Split('.')[0].ToString();
                        Objtbl_ProgramPlayList.IsBonusTrack = true;
                        db.tbl_ProgramPlayList.Add(Objtbl_ProgramPlayList);
                        db.SaveChanges();
                        long pkProgramPlayListId = Objtbl_ProgramPlayList.pkProgramPlayListId;
                        var res = db.Proc_SaveNewTrackforUser(ProgramId, pkProgramPlayListId, 2);
                        return RedirectToAction("Audiotrackviewlist", new { id = ProgramId });
                    }
                }
            }
            catch (Exception ex)
            {
                string test = ex.Message.ToString();

            }
            TempData["ProgramId"] = ProgramId;
            return RedirectToAction("Audioindex", new { id = ProgramId });
            //   return View(tbl_ProgramPlayListModel);
        }


        public ActionResult Editbonusaudiotrack(long? id)
        {

            if (TempData["ProgramId"] != null)
            {
                int ProgramId = Convert.ToInt32(TempData["ProgramId"]);
                ViewBag.ProgramId = ProgramId;
                TempData["ProgramId"] = ProgramId;
            }
            else
            {
                return RedirectToAction("Index", "Programs");
            }
            tbl_ProgramPlayList Objtbl_ProgramPlayList = new tbl_ProgramPlayList();
            try
            {


                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Objtbl_ProgramPlayList = db.tbl_ProgramPlayList.Find(id);
                if (Objtbl_ProgramPlayList == null)
                {
                    return HttpNotFound();
                }
            }
            catch (Exception ex)
            {
                string x = ex.Message.ToString();
                throw;
            }

            return View(Objtbl_ProgramPlayList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Editbonusaudiotrack(tbl_ProgramPlayList tbl_ProgramPlayListModel)
        {
            string fileName = string.Empty;
            string destinationPath = string.Empty;
            string oldDestination = string.Empty;
            string newdestinationPath = string.Empty;
            tbl_ProgramPlayList Result = db.tbl_ProgramPlayList.Where(x => x.pkProgramPlayListId == tbl_ProgramPlayListModel.pkProgramPlayListId).FirstOrDefault();
            if (ModelState.IsValid)
            {


                HttpPostedFileBase file_Uploader = Request.Files[0] as HttpPostedFileBase;
                if (file_Uploader.ContentLength > 0)
                {
                    destinationPath = Path.Combine(Server.MapPath("~/Upload/")); // base path
                    oldDestination = Path.Combine(Server.MapPath("~/Upload/")); //old base path

                    fileName = Path.GetFileName(file_Uploader.FileName).Replace("_", "-");
                    string guidwithFile = Guid.NewGuid().ToString().Substring(0, 20).Replace("_", "-");
                    string strpath = System.IO.Path.GetExtension(file_Uploader.FileName);
                    guidwithFile = guidwithFile + strpath;
                    if (!Result.PlayListUrl.Contains("defaultProgram"))
                    {
                        var OldFilename = new String[4];

                        if (Result.PlayListUrl.Contains('/'))
                        {
                            OldFilename = Result.PlayListUrl.Split('/');
                        }
                        newdestinationPath = Path.Combine(Server.MapPath("~/Upload/" + OldFilename[0].ToString() + "/" + guidwithFile));
                        oldDestination = Path.Combine(Server.MapPath("~/Upload/" + OldFilename[0].ToString() + "/" + OldFilename[1]));
                        Result.PlayListUrl = OldFilename[0].ToString() + "/" + guidwithFile;

App/Views/BonusTrackAdmin/Audiotrackviewlist.cshtml
@*@model IEnumerable<App.Models.tbl_ProgramMaster>*@
@model IEnumerable<App.viewmodel.ProgramPlayListViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}

<h2 class="user_listing-head">Audio Track List</h2>
<p class="create__new-program">
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i> @Html.ActionLink("Create New", "Create")
</p>

<div class="box-body table-responsive no-padding">
    <table class="table table-hover">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.PlayList)

            </th>
            <th>
                Description

            </th>
            <th>
                Created By

            </th>
            <th>
                Download
            </th>

            <th>Action</th>
        </tr>

        @foreach (var item in Model)
        {


            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.PlayList)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)


                </td>

                <td>
                    <a href="~/Upload/@item.TrackUrl" target="_blank">
                        <span class="glyphicon glyphicon-download-alt"></span>
                    </a>
                    <span>@item.TrackTimeCount</span>

                </td>


                <td>
                    @Html.ActionLink("Edit", "Editbonusaudiotrack", new { id = item.pkProgramPlayListId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.pkProgramPlayListId })

                </td>
            </tr>

        }

    </table>
</div>



App/Views/BonusTrackAdmin/Create.cshtml
@model App.Models.tbl_ProgramPlayList

@using (Html.BeginForm("Create", "BonusTrackAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create Bonus Track</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Track Name</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlayList, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlayList, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextArea("Description", new {  @class = "textarea form-control",
               rows = "10",   style = "width:50%;" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Track Artist</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrackArtist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrackArtist, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlayList, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlayList, new { htmlAttributes = new { Type = "File" } })
                @Html.ValidationMessageFor(model => model.PlayList, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Tracks", "Audiotrackviewlist", "BonusTrackAdmin", new { id = @ViewBag.ProgramId }, htmlAttributes: null)
</div>


App/Views/BonusTrackAdmin/Delete.cshtml
@model App.viewmodel.ProgramPlayListViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLteLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

<div>
    <h4>Program</h4>
    <hr />
    @using (Html.BeginForm("delete", "BonusTrackAdmin", FormMethod.Post))
    {

        <dl class="dl-horizontal">
            <dt>
                PlayList
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PlayList)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedBy)
            </dd>

            @Html.Hidden("hdnFlag", null, new { @id = @ViewBag.pkProgramPlayListId })

        </dl>



        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @*@Html.ActionLink("Back to List", "Audioindex/", new { id = Model.fkProgramId })*@
        </div>
    }
</div>



App/Views/BonusTrackAdmin/Editbonusaudiotrack.cshtml
@model App.Models.tbl_ProgramPlayList


<h2>Edit Audio Track</h2>
@using (Html.BeginForm("Editbonusaudiotrack", "BonusTrackAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.pkProgramPlayListId)

        <div class="form-group">
            <label class="control-label col-md-2">Track Name</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlayList, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlayList, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextArea("Description", new {  @class = "textarea form-control",
               rows = "10",   style = "width:50%;" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2">Track Artist</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrackArtist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrackArtist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlayList, "File", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@if (!String.IsNullOrEmpty(Model.ImageUrl))
                    {
                        <img src="@Url.Content("~/Upload/ProgramImages/ActiveProgram/" + Model.ImageUrl)" width="30%" alt="" />
                    }*@
                @Html.EditorFor(model => model.PlayList, new { htmlAttributes = new { Type = "File" } })
                @Html.ValidationMessageFor(model => model.PlayList, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Audioindex")
    @Html.ActionLink("Back to Tracks", "AudioIndex", "AdminTrack", new { id = @ViewBag.ProgramId }, htmlAttributes: null)

</div>
